export const P0_COPY = {
  ua: {
    anySeat:'Будь-яке — підбере менеджер', chooseSeat:'Обрати місце на схемі',
    optionalSeat:'Вибір місця необов’язковий. Менеджер підтвердить місце після заявки.',
    seatsUnavailable:'Схема тимчасово недоступна. Ви можете надіслати заявку — менеджер підбере місце.',
    toDetails:'Заповнити дані', availabilityOptional:'Місце підтвердить менеджер',
    sendFallback:'Не отримано підтвердження заявки. Надішліть готовий текст у WhatsApp або зателефонуйте.',
    sendWhatsApp:'Надіслати у WhatsApp', copyForViber:'Скопіювати заявку для Viber', copied:'Текст заявки скопійовано. Вставте його в чат Viber.',
    phoneError:'Телефон: тільки цифри та +. Для +380 — 12 цифр; для +39 — 11–13.',
    phoneRequired:'Вкажіть телефон, щоб менеджер міг зв’язатися з вами.',
    phoneFormat:'Вкажіть номер з кодом країни, наприклад: +380 67 123 45 67.',
    phoneUaShort:'Номер закороткий. Після +380 має бути 9 цифр. Наприклад: +380 67 123 45 67.',
    phoneUaLong:'Номер задовгий. Після +380 має бути 9 цифр. Наприклад: +380 67 123 45 67.',
    phoneItShort:'Номер закороткий. Після +39 має бути 9–11 цифр. Наприклад: +39 320 123 4567.',
    phoneItLong:'Номер задовгий. Після +39 має бути 9–11 цифр. Наприклад: +39 320 123 4567.',
    phoneShort:'Номер закороткий. Вкажіть код країни та повний номер телефону.',
    phoneLong:'Номер задовгий. Міжнародний номер містить не більше 15 цифр.',
    firstRequired:'Вкажіть ім’я пасажира.', lastRequired:'Вкажіть прізвище пасажира.',
    emailLabel:'Email — необов’язково', emailError:'Перевірте email: наприклад, name@gmail.com.',
    consentError:'Підтвердьте згоду з умовами перевезення та обробкою персональних даних.',
    weeklyUa:'Виїзд: вівторок / середа', weeklyIt:'Виїзд: п’ятниця / субота',
    weekly_tue:'Виїзд щовівторка', weekly_wed:'Виїзд щосереди', weekly_fri:'Виїзд щоп’ятниці', weekly_sat:'Виїзд щосуботи',
    tripDetails:'Деталі рейсу та точки посадки', toPassengers:'До даних пасажирів', seatPickerTitle:'Вибір місця — необов’язково',
    dateNote:'Дата виїзду саме з вашого міста. Час і точку посадки підтвердить менеджер.',
    boarding:'Посадка', dropoff:'Висадка', addressPending:'Точну точку повідомить менеджер',
    payment:'Оплата готівкою водієві при посадці, після підтвердження менеджером.',
    bookingFaq:'Оберіть міста та дату, за бажанням — місце на схемі. Заповніть дані пасажирів і надішліть заявку або напишіть у WhatsApp чи Viber. Якщо схема місць не завантажилася, заявку все одно можна надіслати. Менеджер підтвердить місце.',
    seatSub:'Оберіть місце за бажанням або довірте вибір менеджеру.'
  },
  ru: {
    anySeat:'Любое — подберёт менеджер', chooseSeat:'Выбрать место на схеме',
    optionalSeat:'Выбор места необязателен. Менеджер подтвердит место после заявки.',
    seatsUnavailable:'Схема временно недоступна. Вы можете отправить заявку — менеджер подберёт место.',
    toDetails:'Заполнить данные', availabilityOptional:'Место подтвердит менеджер',
    sendFallback:'Не получено подтверждение заявки. Отправьте готовый текст в WhatsApp или позвоните.',
    sendWhatsApp:'Отправить в WhatsApp', copyForViber:'Скопировать заявку для Viber', copied:'Текст заявки скопирован. Вставьте его в чат Viber.',
    phoneError:'Телефон: только цифры и +. Для +380 — 12 цифр; для +39 — 11–13.',
    phoneRequired:'Укажите телефон, чтобы менеджер мог связаться с вами.',
    phoneFormat:'Укажите номер с кодом страны, например: +380 67 123 45 67.',
    phoneUaShort:'Номер слишком короткий. После +380 должно быть 9 цифр. Например: +380 67 123 45 67.',
    phoneUaLong:'Номер слишком длинный. После +380 должно быть 9 цифр. Например: +380 67 123 45 67.',
    phoneItShort:'Номер слишком короткий. После +39 должно быть 9–11 цифр. Например: +39 320 123 4567.',
    phoneItLong:'Номер слишком длинный. После +39 должно быть 9–11 цифр. Например: +39 320 123 4567.',
    phoneShort:'Номер слишком короткий. Укажите код страны и полный номер телефона.',
    phoneLong:'Номер слишком длинный. Международный номер содержит не больше 15 цифр.',
    firstRequired:'Укажите имя пассажира.', lastRequired:'Укажите фамилию пассажира.',
    emailLabel:'Email — необязательно', emailError:'Проверьте email: например, name@gmail.com.',
    consentError:'Подтвердите согласие с условиями перевозки и обработкой персональных данных.',
    weeklyUa:'Выезд: вторник / среда', weeklyIt:'Выезд: пятница / суббота',
    weekly_tue:'Выезд каждый вторник', weekly_wed:'Выезд каждую среду', weekly_fri:'Выезд каждую пятницу', weekly_sat:'Выезд каждую субботу',
    tripDetails:'Детали рейса и точки посадки', toPassengers:'К данным пассажиров', seatPickerTitle:'Выбор места — необязательно',
    dateNote:'Дата выезда именно из вашего города. Время и точку посадки подтвердит менеджер.',
    boarding:'Посадка', dropoff:'Высадка', addressPending:'Точную точку сообщит менеджер',
    payment:'Оплата наличными водителю при посадке, после подтверждения менеджером.',
    bookingFaq:'Выберите города и дату, по желанию — место на схеме. Заполните данные пассажиров и отправьте заявку или напишите в WhatsApp либо Viber. Если схема мест не загрузилась, заявку всё равно можно отправить. Менеджер подтвердит место.',
    seatSub:'Выберите место по желанию или доверьте выбор менеджеру.'
  },
  it: {
    anySeat:'Qualsiasi — sceglie l’operatore', chooseSeat:'Scegli un posto sulla mappa',
    optionalSeat:'La scelta del posto è facoltativa. L’operatore confermerà il posto dopo la richiesta.',
    seatsUnavailable:'Mappa temporaneamente non disponibile. Puoi comunque inviare la richiesta: l’operatore sceglierà il posto.',
    toDetails:'Inserisci i dati', availabilityOptional:'Il posto sarà confermato dall’operatore',
    sendFallback:'Conferma della richiesta non ricevuta. Invia il testo pronto su WhatsApp oppure chiama.',
    sendWhatsApp:'Invia su WhatsApp', copyForViber:'Copia la richiesta per Viber', copied:'Testo copiato. Incollalo nella chat Viber.',
    phoneError:'Telefono: solo cifre e +. Per +380: 12 cifre; per +39: 11–13.',
    phoneRequired:'Inserisci il telefono per essere contattato dall’operatore.',
    phoneFormat:'Inserisci il numero con prefisso internazionale, ad esempio: +39 320 123 4567.',
    phoneUaShort:'Numero troppo corto. Dopo +380 servono 9 cifre. Esempio: +380 67 123 45 67.',
    phoneUaLong:'Numero troppo lungo. Dopo +380 servono 9 cifre. Esempio: +380 67 123 45 67.',
    phoneItShort:'Numero troppo corto. Dopo +39 servono 9–11 cifre. Esempio: +39 320 123 4567.',
    phoneItLong:'Numero troppo lungo. Dopo +39 servono 9–11 cifre. Esempio: +39 320 123 4567.',
    phoneShort:'Numero troppo corto. Inserisci il prefisso internazionale e il numero completo.',
    phoneLong:'Numero troppo lungo. Il numero internazionale contiene al massimo 15 cifre.',
    firstRequired:'Inserisci il nome del passeggero.', lastRequired:'Inserisci il cognome del passeggero.',
    emailLabel:'Email — facoltativa', emailError:'Controlla l’email: ad esempio, name@gmail.com.',
    consentError:'Accetta le condizioni di trasporto e il trattamento dei dati personali.',
    weeklyUa:'Partenza: martedì / mercoledì', weeklyIt:'Partenza: venerdì / sabato',
    weekly_tue:'Partenza ogni martedì', weekly_wed:'Partenza ogni mercoledì', weekly_fri:'Partenza ogni venerdì', weekly_sat:'Partenza ogni sabato',
    tripDetails:'Dettagli della corsa e punti di salita', toPassengers:'Vai ai dati dei passeggeri', seatPickerTitle:'Scelta del posto — facoltativa',
    dateNote:'Data di partenza dalla tua città. L’operatore confermerà ora e punto di salita.',
    boarding:'Salita', dropoff:'Discesa', addressPending:'Il punto esatto sarà comunicato dall’operatore',
    payment:'Pagamento in contanti all’autista alla salita, dopo la conferma dell’operatore.',
    bookingFaq:'Scegli città e data e, se vuoi, un posto sulla mappa. Inserisci i dati dei passeggeri e invia la richiesta oppure scrivi su WhatsApp o Viber. Puoi inviare la richiesta anche se la mappa non si carica. L’operatore confermerà il posto.',
    seatSub:'Scegli un posto se vuoi, oppure lascia la scelta all’operatore.'
  }
};
